# Generated by Django 5.2.8 on 2025-11-21 10:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_fees_feepayment_importlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='resume',
            name='non_tech_resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/non_tech/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tech_resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/tech/'),
        ),
        migrations.CreateModel(
            name='SemesterPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_performances', to='erp.student')),
            ],
            options={
                'ordering': ['semester'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
