# Generated by Django 5.2.8 on 2025-11-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_resume_resume_file_resume_non_tech_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='non_tech_resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='tech_resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
