# Generated by Django 5.2.8 on 2025-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_degree_alter_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='university_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
