# Generated by Django 5.2.8 on 2025-11-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_degree_university_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('lecture1', models.TimeField(blank=True, null=True)),
                ('lecture2', models.TimeField(blank=True, null=True)),
                ('lecture3', models.TimeField(blank=True, null=True)),
                ('lecture4', models.TimeField(blank=True, null=True)),
                ('lecture5', models.TimeField(blank=True, null=True)),
                ('lecture6', models.TimeField(blank=True, null=True)),
                ('lecture7', models.TimeField(blank=True, null=True)),
                ('lunch', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.degree')),
            ],
            options={
                'unique_together': {('degree', 'section')},
            },
        ),
    ]
