# Generated by Django 5.2.8 on 2025-11-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='lecture1_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_lecture1', to='erp.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecture2_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_lecture2', to='erp.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecture3_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_lecture3', to='erp.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecture4_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_lecture4', to='erp.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecture5_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_lecture5', to='erp.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecture6_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_lecture6', to='erp.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecture7_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_lecture7', to='erp.subject'),
        ),
    ]
