# Generated by Django 5.2.7 on 2025-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='active_days',
            field=models.CharField(blank=True, default='mon,tue,wed,thu,fri,sat', max_length=100),
        ),
    ]
