# Generated by Django 5.2.8 on 2025-11-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_timetable_active_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
