# Generated by Django 5.2.7 on 2025-12-02 09:58

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8)
                ],
                null=True,
                blank=True,
                help_text='Semester for which this timetable is applicable'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('degree', 'section', 'semester')},
        ),
    ]
